var faker = require('faker')
var dish= {dishes:[
    {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    }, {
      name: faker.name.findName(),
      price: faker.commerce.price(),
      ingredients: faker.lorem.words()
    },
  ]
}
export default dish